name: github_starz

on:
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * 1

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.0
    - name: Install lbxml dependencies
      run: sudo apt-get install -y libxslt-devel libxml2-devel
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run GitHub Starz script
      env:
        PERSONAL_GITHUB_ACCESS_TOKEN: '${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}'
      run: |
        python github_starz.py
