name: github_starz

on:
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * 1

jobs:
  setup:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run discovered weekly
      env:
        PERSONAL_ACCESS_TOKEN: '${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}'
      run: |
        python github_starz.py
